---
- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        fail2ban_exporter_web_listen_address is string

- name: Naive assertion of proper listen address
  ansible.builtin.assert:
    that:
      - >-
        [fail2ban_exporter_web_listen_address] |
          flatten |
          reject('match', '.+:\\d+$') |
          list |
          length == 0

- name: Check if fail2ban_exporter is installed
  ansible.builtin.stat:
    path: "{{ fail2ban_exporter_binary_install_dir }}/fail2ban_exporter"
  register: __fail2ban_exporter_is_installed
  check_mode: false
  tags:
    - fail2ban_exporter_install

- name: Gather currently installed fail2ban_exporter version (if any)
  ansible.builtin.command: "{{ fail2ban_exporter_binary_install_dir }}/fail2ban_exporter --version"
  changed_when: false
  register: __fail2ban_exporter_current_version_output
  check_mode: false
  when: __fail2ban_exporter_is_installed.stat.exists
  tags:
    - fail2ban_exporter_install

- name: Discover latest version
  ansible.builtin.set_fact:
    fail2ban_exporter_version: "{{ (lookup('url', 'https://gitlab.com/api/v4/projects/{{ _fail2ban_exporter_repo }}/releases',
                                split_lines=False) | from_json)[0].get('tag_name') | replace('v', '') }}"
  run_once: true
  until: fail2ban_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - fail2ban_exporter_version == "latest"
    - not fail2ban_exporter_skip_download
  tags:
    - fail2ban_exporter_install
