---
namespace: prometheus
name: prometheus
version: 2.0.6
readme: README.md
authors:
  - "Ben Kochie (https://github.com/SuperQ)"
  - "Paweł Krupa (https://github.com/paulfantom)"
description: "Ansible Collection for Prometheus"
license_file: LICENSE
tags:
  - observability
  - o11y
  - monitoring
  - prometheus
  - metrics
  - alerts
  - alerting
  - cloud
dependencies:
  community.crypto: '>=2.0.0'
  community.general: '>=1.0.0'
repository: "https://github.com/prometheus-community/ansible"
documentation: "https://github.com/prometheus-community/ansible/blob/main/docs"
homepage: "https://prometheus.io"
issues: "https://github.com/prometheus-community/ansible/issues"
build_ignore:
  - 'tests/*'
  - '*.tar.gz'
  - 'docs/*'
