---
- name: Prepare
  hosts: localhost
  gather_facts: false
  vars:
    # This is meant to test a local prepared binary. It needs to be updated to support the minium
    # flag features in the systemd service file.
    version: 2.25.2
  tasks:
    - name: Download prometheus binary to local folder
      become: false
      ansible.builtin.get_url:
        url: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
        dest: "/tmp/prometheus-{{ version }}.linux-amd64.tar.gz"
        mode: 0644
      register: _download_archive
      until: _download_archive is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: Unpack prometheus binaries
      become: false
      ansible.builtin.unarchive:
        src: "/tmp/prometheus-{{ version }}.linux-amd64.tar.gz"
        dest: "/tmp"
        creates: "/tmp/prometheus-{{ version }}.linux-amd64/prometheus"
      check_mode: false

    - name: Link to prometheus binaries directory
      become: false
      ansible.builtin.file:
        src: "/tmp/prometheus-{{ version }}.linux-amd64"
        dest: "/tmp/prometheus-linux-amd64"
        state: link
      check_mode: false
