---
- name: Copy the cadvisor systemd service file
  ansible.builtin.template:
    src: cadvisor.service.j2
    dest: /etc/systemd/system/cadvisor.service
    owner: root
    group: root
    mode: 0644
  notify: restart cadvisor
