---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - cadvisor_install
        - cadvisor_configure
        - cadvisor_run
  tags:
    - cadvisor_install
    - cadvisor_configure
    - cadvisor_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
    apply:
      become: true
      tags:
        - cadvisor_install
  vars:
    _common_local_cache_path: "{{ cadvisor_local_cache_path }}"
    _common_binaries: "{{ _cadvisor_binaries }}"
    _common_binary_install_dir: "{{ _cadvisor_binary_install_dir }}"
    _common_binary_local_dir: "{{ cadvisor_binary_local_dir }}"
    _common_binary_url: "{{ cadvisor_binary_url }}"
    _common_system_group:  "{{ cadvisor_system_group }}"
    _common_system_user:  "{{ cadvisor_system_user }}"
  tags:
    - cadvisor_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
    apply:
      tags:
        - cadvisor_configure
  vars:
    _common_selinux_port: "{{ cadvisor_port }}"
  when: ansible_selinux.status == "enabled"
  tags:
    - cadvisor_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - cadvisor_configure
  tags:
    - cadvisor_configure

- name: Ensure cAdvisor is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: cadvisor
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - cadvisor_run
