---
- name: Preflight
  ansible.builtin.include_tasks: preflight.yml
  tags:
    - blackbox_exporter_install
    - blackbox_exporter_configure
    - blackbox_exporter_run

- name: Install
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      become: true
  tags:
    - blackbox_exporter_install

- name: Configure
  ansible.builtin.include_role:
    name: prometheus.prometheus.common
    tasks_from: configure.yml
    apply:
      become: true
  vars:
    _system_user: "{{ blackbox_exporter_system_user }}"
    _system_group: "{{ blackbox_exporter_system_group }}"
  tags:
    - blackbox_exporter_configure

- name: Ensure blackbox_exporter service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: blackbox_exporter
    state: started
    enabled: true
  tags:
    - blackbox_exporter_run
