---
- name: Common preflight
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: preflight.yml

- name: Assert that used version supports listen address type
  ansible.builtin.assert:
    that:
      - >-
        snmp_exporter_web_listen_address is string
        or
        (
          snmp_exporter_version is version('0.21.0', '>=') and
          snmp_exporter_web_listen_address | type_debug == "list"
        )

- name: Naive assertion of proper listen address
  ansible.builtin.assert:
    that:
      - >-
        [snmp_exporter_web_listen_address] |
          flatten |
          reject('match', '.+:\\d+$') |
          list |
          length == 0

- name: Discover latest version
  ansible.builtin.set_fact:
    snmp_exporter_version: "{{ (lookup('url', 'https://api.github.com/repos/{{ _snmp_exporter_repo }}/releases/latest', headers=_github_api_headers,
                            split_lines=False) | from_json).get('tag_name') | replace('v', '') }}"
  run_once: true
  until: snmp_exporter_version is version('0.0.0', '>=')
  retries: 10
  when:
    - snmp_exporter_version == "latest"
    - not snmp_exporter_skip_download
  tags:
    - snmp_exporter_install
