---
- name: Run role
  hosts: all
  any_errors_fatal: true
  roles:
    - prometheus.prometheus.node_exporter
  pre_tasks:
    - name: Create node_exporter cert dir
      ansible.builtin.file:
        path: "{{ node_exporter_tls_server_config.cert_file | dirname }}"
        state: directory
        owner: root
        group: root
        mode: u+rwX,g+rwX,o=rX

    - name: Copy cert and key
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode | default('0644') }}"
      loop:
        - src: "/tmp/tls.cert"
          dest: "{{ node_exporter_tls_server_config.cert_file }}"
        - src: "/tmp/tls.key"
          dest: "{{ node_exporter_tls_server_config.key_file }}"
