---
- name: "Common configure"
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: configure.yml

- name: Create bind_exporter config directory
  ansible.builtin.file:
    path: "{{ bind_exporter_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX

- name: Configure bind_exporter web config
  when:
    ( bind_exporter_tls_server_config | length > 0 ) or
    ( bind_exporter_http_server_config | length > 0 ) or
    ( bind_exporter_basic_auth_users | length > 0 )
  block:
    - name: Copy the bind_exporter web config file
      ansible.builtin.template:
        src: web_config.yaml.j2
        dest: "{{ bind_exporter_config_dir }}/web_config.yaml"
        owner: root
        group: '{{ bind_exporter_system_group }}'
        mode: '0640'
      notify: restart bind_exporter
