---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - bind_exporter_install
        - bind_exporter_configure
        - bind_exporter_run
  tags:
    - bind_exporter_install
    - bind_exporter_configure
    - bind_exporter_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
    apply:
      become: true
      tags:
        - bind_exporter_install
  vars:
    _common_local_binary_cache_path: "{{ bind_exporter_archive_path }}"
    _common_binaries: "{{ _bind_exporter_binaries }}"
    _common_binary_install_dir: "{{ _bind_exporter_binary_install_dir }}"
    _common_binary_local_dir: "{{ bind_exporter_binary_local_dir }}"
    _common_binary_url: "{{ bind_exporter_binary_url }}"
    _common_checksums_url: "{{ bind_exporter_checksums_url }}"
    _common_system_group:  "{{ bind_exporter_system_group }}"
    _common_system_user:  "{{ bind_exporter_system_user }}"
  tags:
    - bind_exporter_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
    apply:
      tags:
        - bind_exporter_configure
  vars:
    _common_selinux_port: "{{ bind_exporter_web_listen_address | urlsplit('port') }}"
  when: ansible_selinux.status == "enabled"
  tags:
    - bind_exporter_configure

- name: SELinux
  ansible.builtin.include_tasks:
    file: selinux.yml
    apply:
      become: true
      tags:
        - bind_exporter_configure
  when: ansible_selinux.status == "enabled"
  tags:
    - bind_exporter_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - bind_exporter_configure
  tags:
    - bind_exporter_configure

- name: Ensure BIND Exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: bind_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - bind_exporter_run
