---
- name: Register service name
  ansible.builtin.set_fact:
    __common_service_name: "{{ ansible_parent_role_names | first | regex_replace(ansible_collection_name ~ '.', '') }}"
    __common_binary_archive: "{{ _common_binary_url | urlsplit('path') | basename }}"

- name: Create system group
  ansible.builtin.group:
    name: "{{ _common_system_group }}"
    system: true
    state: present

- name: Create alertmanager system user
  ansible.builtin.user:
    name: "{{ _common_system_user }}"
    system: true
    shell: "/usr/sbin/nologin"
    group: "{{ _common_system_group }}"
    createhome: false

- name: Download and install from binary
  when:
    - _common_binary_local_dir | length == 0
  block:
    - name: "Get checksum list"
      ansible.builtin.set_fact:
        #        __common_binary_checksums: "{{ dict(lookup('url', _common_checksums_url, headers=_common_github_api_headers, wantlist=True) |
        #                            map('regex_replace', '^([a-fA-F0-9]+)\\s+', 'sha256:\\1 ') | map('split', ' ') | map('reverse')) }}"
        __common_binary_checksums: "{{ dict(lookup('url', _common_checksums_url, headers=_common_github_api_headers, wantlist=True)
                                    | map('regex_replace', '^([a-fA-F0-9]+)\\s+', 'sha256:\\1 ')
                                    | map('regex_findall', '^(sha256:[a-fA-F0-9]+)\\s+(.+)$') | map('flatten') | map('reverse')) }}"
      run_once: true
      when: (_common_checksums_url)

    - name: Download binary archive to local folder
      become: false
      ansible.builtin.get_url:
        url: "{{ _common_binary_url }}"
        dest: "{{ _common_archive_path }}/{{ __common_binary_archive }}"
        headers: "{{ _common_github_api_headers }}"
        checksum: "{{ __common_binary_checksums[__common_binary_archive] | default(omit) }}"
        mode: 0644
      register: __common_download_archive
      until: __common_download_archive is succeeded
      retries: 5
      delay: 2
      # run_once: true  # <-- this can't be set due to multi-arch support
      delegate_to: localhost
      check_mode: false

    - name: Unpack binary archive
      become: false
      ansible.builtin.unarchive:
        src: "{{ _common_archive_path }}/{{ __common_binary_archive }}"
        dest: "{{ _common_archive_path }}"
        mode: 0755
        list_files: true
      register: __common_unpack
      delegate_to: localhost
      check_mode: false

- name: Debug download
  ansible.builtin.debug:
    msg:
      - "__common_download_archive {{ __common_download_archive }}"
      - "__common_archive_content {{ __common_archive_content }}"
      - "__common_unpack {{ __common_unpack | default('') }}"
      - "_common_binary_url {{ _common_binary_url }}"
      - "__common_binary_archive {{ __common_binary_archive }}"
  failed_when: false
  vars:
    __common_archive_content: "{{ [_common_archive_path ~ '/' ] | product(__common_unpack.files | default([])) | map('join') | list }}"

- name: Debug binary src
  ansible.builtin.debug:
    msg:
      - "binary src__ {{ (_common_binary_local_dir ~ '/' ~ item) | default(__common_archive_content | select('search', item + '$') | first) }}"
      - "{{ (_common_binary_local_dir) | ternary((_common_binary_local_dir  ~ '/' ~ item), (__common_archive_content | select('search', item + '$') | first)) }}"
      - "binary src__ def true {{ (_common_binary_local_dir ~ '/' ~ item) | default(__common_archive_content | select('search', item + '$') | first, true) }}"
      - "common local dir {{ (_common_binary_local_dir ~ '/' ~ item) }}"
      - "common arch content {{ __common_archive_content | select('search', item + '$') | first }}"
  loop: "{{ _common_binaries }}"
  failed_when: false
  vars:
    __common_archive_content: "{{ [_common_archive_path ~ '/' ] | product(__common_unpack.files | default([])) | map('join') | list }}"

- name: Debug checksum
  ansible.builtin.debug:
    msg:
      - "{{ __common_binary_checksums[__common_binary_archive] | default(omit) }}"
  loop: "{{ _common_binaries }}"
  failed_when: false
  vars:
    __common_archive_content: "{{ [_common_archive_path ~ '/' ] | product(__common_unpack.files | default([])) | map('join') | list }}"

- name: Propagate binaries
  ansible.builtin.copy:
    src: "{{ (_common_binary_local_dir) | ternary((_common_binary_local_dir ~ '/' ~ item),
          (__common_archive_content | select('search', item + '$') | first)) }}"
    dest: "{{ _common_binary_install_dir }}/{{ item }}"
    mode: 0755
    owner: root
    group: root
  loop: "{{ _common_binaries }}"
  notify:
    - restart_service
  vars:
    __common_archive_content: "{{ [_common_archive_path ~ '/' ] | product(__common_unpack.files | default([])) | map('join') | list }}"
