---
- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _common_dependencies }}"
    state: present
  when: (_common_dependencies)

- name: Gather package facts
  ansible.builtin.package_facts:
  when: "not 'packages' in ansible_facts"
