---
- name: "Validate invocation of _common role"
  ansible.builtin.assert:
    that:
      - "ansible_parent_role_names is defined"
      - "ansible_parent_role_names | default() | length > 0"
    fail_msg: "Error: The '_common' role is a internal role and cannot be invoked directly."

- name: Assert usage of systemd as an init system
  ansible.builtin.assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This module only works with systemd"

- name: Install dependencies
  become: true
  ansible.builtin.package:
    name: "{{ _common_dependencies }}"
    state: present
  when: (_common_dependencies)

- name: Gather package facts
  ansible.builtin.package_facts:
  when: "not 'packages' in ansible_facts"
