---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - prometheus_configure
        - prometheus_install
        - prometheus_run
  tags:
    - prometheus_configure
    - prometheus_install
    - prometheus_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
    apply:
      become: true
      tags:
        - prometheus_install
  vars:
    _common_local_cache_path: "{{ prometheus_local_cache_path }}"
    _common_binaries: "{{ _prometheus_binaries }}"
    _common_skip_download: "{{ prometheus_skip_download }}"
    _common_binary_install_dir: "{{ prometheus_binary_install_dir }}"
    _common_binary_url: "{{ prometheus_binary_url }}"
    _common_checksums_url: "{{ prometheus_checksums_url }}"
    _common_system_group:  "{{ prometheus_system_group }}"
    _common_system_user:  "{{ prometheus_system_user }}"
    _common_config_dir: "{{ prometheus_config_dir }}"
    _common_binary_unarchive_opts: ['--strip-components=1']
  tags:
    - prometheus_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
    apply:
      tags:
        - prometheus_configure
  vars:
    _common_selinux_port: "{{ prometheus_web_listen_address | urlsplit('port') }}"
  when: ansible_selinux.status == "enabled"
  tags:
    - prometheus_configure

- name: Configure
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - prometheus_configure
  tags:
    - prometheus_configure

- name: Ensure prometheus service is started and enabled
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
  register: __prometheus_systemctl_start
  tags:
    - prometheus_run

- name: Wait a minute before checking service status
  ansible.builtin.pause:
    minutes: 1

- name: "Debug - check prometheus service status"
  ansible.builtin.command:
    cmd: "systemctl status prometheus"
  changed_when: false
  failed_when: false
  register: __prometheus_systemctl_status

- name: "Debug - print service start"
  ansible.builtin.debug:
    var: __prometheus_systemctl_start

- name: "Debug - print service status"
  ansible.builtin.debug:
    var: __prometheus_systemctl_status

- name: "Check prometheus config"
  ansible.builtin.slurp:
    src: "{{ prometheus_config_dir }}/prometheus.yml"
  register: __prometheus_yml

- name: "Check prometheus service config"
  ansible.builtin.slurp:
    src: "/etc/systemd/system/{{ _common_service_name }}.service"
  register: __prometheus_service_conf

- name: "Debug - print prometheus config"
  ansible.builtin.debug:
    msg: "{{ __prometheus_yml['content'] | to_nice_yaml }}"

- name: "Debug - print prometheus service"
  ansible.builtin.debug:
    msg: "{{ __prometheus_service_conf['content'] }}"
