---
- name: Preflight
  ansible.builtin.include_tasks:
    file: preflight.yml
    apply:
      tags:
        - nginx_exporter_install
        - nginx_exporter_configure
        - nginx_exporter_run
  tags:
    - nginx_exporter_install
    - nginx_exporter_configure
    - nginx_exporter_run

- name: Install
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: install.yml
    apply:
      become: true
      tags:
        - nginx_exporter_install
  vars:
    _common_local_cache_path: "{{ nginx_exporter_local_cache_path }}"
    _common_binary_name: "{{ _nginx_exporter_binaries | first }}"
    _common_binaries: "{{ _nginx_exporter_binaries }}"
    _common_skip_download: "{{ nginx_exporter_skip_download }}"
    _common_binary_install_dir: "{{ nginx_exporter_binary_install_dir }}"
    _common_binary_url: "{{ nginx_exporter_binary_url }}"
    _common_checksums_url: "{{ nginx_exporter_checksums_url }}"
    _common_system_group:  "{{ nginx_exporter_system_group }}"
    _common_system_user:  "{{ nginx_exporter_system_user }}"
    _common_config_dir: "{{ nginx_exporter_config_dir }}"
  tags:
    - nginx_exporter_install

- name: SELinux
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: selinux.yml
    apply:
      tags:
        - nginx_exporter_configure
  vars:
    _common_selinux_port: "{{ nginx_exporter_web_listen_address | urlsplit('port') }}"
  when: ansible_selinux.status == "enabled"
  tags:
    - nginx_exporter_configure

- name: Configure
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: configure.yml
    apply:
      tags:
        - nginx_exporter_configure
  vars:
    _common_system_user: "{{ nginx_exporter_system_user }}"
    _common_system_group: "{{ nginx_exporter_system_group }}"
    _common_config_dir: "{{ nginx_exporter_config_dir }}"
    _common_tls_server_config: "{{ nginx_exporter_tls_server_config }}"
    _common_http_server_config: "{{ nginx_exporter_http_server_config }}"
    _common_basic_auth_users: "{{ nginx_exporter_basic_auth_users }}"
  tags:
    - nginx_exporter_configure

- name: Ensure nginx_exporter is enabled on boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: nginx_exporter
    enabled: true
    state: started
  when:
    - not ansible_check_mode
  tags:
    - nginx_exporter_run
