---
- name: "Common configure"
  ansible.builtin.include_role:
    name: prometheus.prometheus._common
    tasks_from: configure.yml

- name: Create chrony_exporter config directory
  ansible.builtin.file:
    path: "/etc/chrony_exporter"
    state: directory
    owner: root
    group: root
    mode: u+rwX,g+rwX,o=rX

- name: Copy the chrony_exporter web config file
  ansible.builtin.template:
    src: web_config.yaml.j2
    dest: /etc/chrony_exporter/web_config.yaml
    owner: root
    group: root
    mode: 0644
  notify: restart chrony_exporter
