---
dependency:
  name: galaxy
prerun: false
driver:
  name: docker
platforms:
  - name: almalinux-8
    image: dokken/almalinux-8
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: almalinux-9
    image: dokken/almalinux-9
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: centos-stream-9
    image: dokken/centos-stream-9
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: debian-11
    image: dokken/debian-11
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: fedora-39
    image: dokken/fedora-39
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: fedora-40
    image: dokken/fedora-40
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-20.04
    image: dokken/ubuntu-20.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-22.04
    image: dokken/ubuntu-22.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
  - name: ubuntu-24.04
    image: dokken/ubuntu-24.04
    pre_build_image: true
    privileged: true
    cgroup_parent: docker.slice
    command: /lib/systemd/systemd
verifier:
  name: testinfra
provisioner:
  playbooks:
    converge: "${MOLECULE_PROJECT_DIRECTORY}/../../.config/molecule/converge.yml"
  inventory:
    hosts:
      target_hosts:
        hosts: []
    host_vars:
      fedora-39:
        exclude_ansible_vers:
          - "2.9"
          - "2.10"
          - "2.11"
      fedora-40:
        exclude_ansible_vers:
          - "2.9"
          - "2.10"
          - "2.11"
      ubuntu-24.04:
        exclude_ansible_vers:
          - "2.9"
          - "2.10"
          - "2.11"
