---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-18.04
    pre_build_image: true
    image: dokken/ubuntu-18.04
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: ubuntu-16.04
    pre_build_image: true
    image: dokken/ubuntu-16.04
    command: /bin/systemd
    privileged: true
    cgroup_parent: docker.slice
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: debian-9
    pre_build_image: true
    image: dokken/debian-9
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-10
    pre_build_image: true
    image: dokken/debian-10
    privileged: true
    cgroup_parent: docker.slice
  - name: centos-7
    pre_build_image: true
    image: dokken/centos-7
    command: /usr/lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: centos-stream-8
    pre_build_image: true
    image: dokken/centos-stream-8
    privileged: true
    command: /lib/systemd/systemd
  - name: almalinux-8
    image: dokken/almalinux-8
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
  - name: debian-11
    image: dokken/debian-11
    pre_build_image: true
    command: /lib/systemd/systemd
    privileged: true
    cgroup_parent: docker.slice
 - name: fedora-30
   pre_build_image: true
   image: dokken/fedora-30
   privileged: true
   command: /lib/systemd/systemd
   cgroup_parent: docker.slice
provisioner:
  name: ansible
  playbooks:
    prepare: prepare.yml
    converge: playbook.yml
verifier:
  name: testinfra
