---
name: Ansible Test
on: [push, pull_request]

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  discover-tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.set-tests.outputs.tests }}
      test_names: ${{ steps.set-tests.outputs.test_names }}
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3

      - name: Discover tests
        id: set-tests
        # Find path to all tests
        run: |
          echo tests="[`for x in $(ls -1 tests/integration/targets); do echo "'$x'"; done | tr '\n' ',' | sed '$s/,$//'`]" >> $GITHUB_OUTPUT
          echo test_names="[`for x in $(ls -1 tests/integration/targets); do echo "'${x//-molecule-/(})'"; done | tr '\n' ',' | sed '$s/,$//'`]" >> $GITHUB_OUTPUT


  molecule:
    name: "molecule: ${{ matrix.test_name }}"
    runs-on: ubuntu-latest
    needs:
      - discover-tests
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(needs.discover-tests.outputs.tests) }}
        test_name: ${{ fromJson(needs.discover-tests.outputs.test_names) }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Perform integration testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.14
          target-python-version: 3.8
          controller-python-version: auto
          docker-image: "--docker-privileged"
          testing-type: integration
          target: ${{ matrix.test }}

  ansible-test-sanity:
    name: ansible-test-sanity
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.14
          testing-type: sanity
