---
name: Ansible Test
# on: [push, pull_request]
on:
  workflow_call:
    inputs:
      integration_tests:
        required: true
        type: string

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJson(inputs.integration_tests) }}

    name: "${{ matrix.test.name }}"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Perform molecule integration testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.14
          target-python-version: 3.8
          controller-python-version: auto
          docker-image: "--docker-privileged"
          testing-type: integration
          target: ${{ matrix.test.test }}
