---
name: Ansible Lint
on: [push, pull_request]

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Lint collection
        uses: ansible/ansible-lint-action@main
