---
name: Ansible changelog
on:
  workflow_dispatch:
  push:
    branches:
      - antsichaut

jobs:
  antsichaut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install antsibull tools"
        run: "python -m pip install antsibull-changelog --disable-pip-version-check"

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Calculate next version"
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Generate new version in changelog.yaml"
        run: antsibull-changelog release -v --version "${{ steps.version.outputs.next-version }}"

      - name: "Run antsichaut"
        uses: rndmh3ro/antsichaut-action@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          since_version: "${{ steps.previoustag.outputs.tag }}"

      - name: "Update Changelog.rst"
        run: "antsibull-changelog generate -v"

      - name: "push changelog"
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'antsichaut'
          commit-message: 'update changelog'
          force-add: 'true'
          files: CHANGELOG.rst changelogs/
          name: Prometheus
          email: noreply@prometheus.io
          rebase: true
