---
name: Ansible changelog
on:
  pull_request:
    types:
      - closed

jobs:
  antsichaut:
    if: github.event.pull_request.merged && github.ref == github.event.repository.default_branch
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install tools"
        run: "python -m pip install ansible-base antsibull-changelog --disable-pip-version-check"

      - name: "Calculate next version"
        id: version
        uses: "gardar/version-drafter-action@event-triggers"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Check git repo before changelog"
        run: git status

      - name: "Generate new version in changelog.yaml"
        run: antsibull-changelog release -v --version "${{ steps.version.outputs.next-version }}"

      - name: "Run antsichaut"
        uses: rndmh3ro/antsichaut-action@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          since_version: "${{ steps.version.outputs.current-version }}"

      - name: "Update Changelog.rst"
        run: "antsibull-changelog generate -v"

      - name: "Update collection version"
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.version.outputs.next-version }}"' 'galaxy.yml'

      - name: "Check git repo"
        run: git status

      - name: "Write changelog and version"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: ${{ github.event.pull_request.base.ref }}

      - name: "Checkout updated branch"
        uses: actions/checkout@v3.3.0

      - name: "Build the collection"
        run: ansible-galaxy collection build

      - name: "Publish release"
        id: release-publish
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true

      - name: "Upload built collection to release"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: prometheus-prometheus-*.tar.gz
          file_glob: true
          tag: ${{ steps.release-publish.outputs.tag_name }}
          overwrite: true
