---
name: Ansible changelog
on: [push, pull_request]

jobs:
  antsichaut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: 'Run antsichaut'
        uses: rndmh3ro/antsichaut-action@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          since_version: "${{ steps.previoustag.outputs.tag }}"
