---
name: Ansible changelog
on:
  workflow_dispatch:
  push:
    branches:
      - antsichaut

jobs:
  antsichaut:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Install tools"
        run: "python -m pip install ansible-base antsibull-changelog --disable-pip-version-check"

      - name: "Get Previous tag"
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@master"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Calculate next version"
        id: version
        uses: patrickjahns/version-drafter-action@v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Generate new version in changelog.yaml"
        run: antsibull-changelog release -v --version "${{ steps.version.outputs.next-version }}"

      - name: "Run antsichaut"
        uses: rndmh3ro/antsichaut-action@main
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          since_version: "${{ steps.previoustag.outputs.tag }}"

      - name: "Update Changelog.rst"
        run: "antsibull-changelog generate -v"

      - name: "Update collection version"
        uses: mikefarah/yq@master
        with:
          cmd: yq -i '.version = "${{ steps.version.outputs.next-version }}"' 'galaxy.yml'

      - name: "push changelog"
        uses: github-actions-x/commit@v2.9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: 'antsichaut'
          commit-message: 'update changelog'
          force-add: 'true'
          files: galaxy.yml CHANGELOG.rst changelogs/
          rebase: true

      - name: "Checkout updated branch"
        uses: actions/checkout@v3.3.0
        with:
          ref: antsichaut

      - name: "Build the collection"
        run: ansible-galaxy collection build

      - name: "Publish release"
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: true

      - name: "Upload built collection to release"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: prometheus-prometheus-*.tar.gz
          file_glob: true
          tag: ${{ github.ref }}
          overwrite: true
