---
name: ci
on: [push, pull_request]

jobs:
  ansible-test-sanity:
    name: ansible-test-sanity
    runs-on: ubuntu-latest
    steps:
      - name: Perform sanity testing with ansible-test
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: stable-2.14
          testing-type: sanity

  discover-molecule-tests:
    runs-on: ubuntu-latest
    needs:
      - ansible-test-sanity
    outputs:
      molecule-tests: ${{ steps.set-tests.outputs.ansible-test-molecule }}
      integration-tests: ${{ steps.set-tests.outputs.ansible-test-integration }}
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
      - name: Discover tests
        id: set-tests
        run: |
          echo ansible-test-molecule="[`for x in $(find tests/integration/targets -maxdepth 1 -mindepth 1 -type d -iname "molecule-*" -printf "%f\n"); do echo '{"test":\"'"${x}"'\","name":\"'"${x#*-}\"'"}'; done | tr '\n' ',' | sed '$s/,$//'`]" >> $GITHUB_OUTPUT
          echo ansible-test-integration="[`for x in $(find tests/integration/targets -maxdepth 1 -mindepth 1 -type d -not -iname "molecule-*" -printf "%f\n"); do echo '{"test":\"'"${x}"'\","name":\"'"${x}\"'"}'; done | tr '\n' ',' | sed '$s/,$//'`]" >> $GITHUB_OUTPUT

  ansible-test-molecule:
    uses: ./.github/workflows/ansible-test.yml
    needs:
      - ansible-test-sanity
      - discover-molecule-tests
    with:
      targets: ${{ needs.discover-molecule-tests.outputs.molecule-tests }}

  ansible-test-integration:
    uses: ./.github/workflows/ansible-test.yml
    needs:
      - ansible-test-sanity
      - discover-molecule-tests
    with:
      targets: ${{ needs.discover-molecule-tests.outputs.integration-tests }}
      ansible-core-versions: '["stable-2.9","stable-2.10","stable-2.11","stable-2.12","stable-2.13","stable-2.14"]'
      target-python-versions: '["3.8","3.9"]'
