---
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]
name: Auto label pull request
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: "Confirm correct pull request title"
        uses: deepakputhraya/action-pr-title@master
        with:
          allowed_prefixes: 'feat,fix,major,breaking,minor,enhancement,deprecated,removed,security,bug,bugfix,docs,packaging,test,refactor,refactoring,skip-release'

      - name: "Apply label"
        if: github.event.pull_request.labels.length == 0
        uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: |
              {
              "feat": "enhancement",
              "fix": "bugfix",
              "major": "major",
              "breaking": "breaking",
              "minor": "minor",
              "enhancement": "enhancement",
              "deprecated": "deprecated",
              "removed": "removed",
              "security": "security",
              "bug": "bug",
              "bugfix": "bugfix",
              "docs": "trivial",
              "packaging": "trivial",
              "test": "trivial",
              "refactor": "trivial",
              "refactoring": "trivial",
              "skip-release": "skip-release"
              }
