---
name: Python Version
# on: [push, pull_request]
on:
  workflow_call:
    inputs:
      targets:
        required: true
        type: string
      ansible-core-versions:
        required: false
        default: '["stable-2.14"]'
        type: string
      target-python-versions:
        required: false
        default: '["3.8"]'
        type: string

env:
  ANSIBLE_FORCE_COLOR: true

jobs:
  check-out:
    steps:
      - name: Check out codebase
        uses: actions/checkout@v3
  ansible-test-integration:
    runs-on: ubuntu-latest
    uses: ./.github/workflows/ansible-test.yml
    with:
      targets: ${{ inputs.targets }}
